### ISSUE TITLE
FOV doesn't reset when "hold to aim" is enabled under TTT2 gameplay options

### ISSUE THREAD

**Issue by TheFestiveGoose** [wgetJane/ttt-weapon-rework#2]
First, love the mod. I've been looking for something like this for a long time.

I noticed a bug when "Enable hold to him" is enabled under TTT2 gameplay options that the fov doesn't reset after zooming with a weapon.

Basically, it doesn't un-zoom.

Let me know if you need any more details

**Comment by wgetJane** [comment]
is it only the fov? does the scope and etc function correctly?

**Comment by wgetJane** [comment]
this appears to be caused by this (which is intended to fix a bug with the fov zooming in slightly whenever a zoomable weapon is deployed/holstered)
https://github.com/wgetJane/ttt-weapon-rework/blob/7521132e0f15178583438fe7a93bb5d9f0b641a7/lua/tttwr/sh_mkzoomable.lua#L25-L27

**Comment by wgetJane** [comment]
@TheFestiveGoose it seems to be caused by this, which fixes a bug with zoomable weapons where they zoom in slightly whenever they're equipped, dropped, reloaded, or holstered
https://github.com/wgetJane/ttt-weapon-rework/blob/7521132e0f15178583438fe7a93bb5d9f0b641a7/lua/tttwr/sh_mkzoomable.lua#L25-L27
